from .admin_handlers import *
from .feedback_handlers import *
from .main_menu_handlers import *
from .chat_handlers import *
from .practice_handlers import *
from .advice_handlers import *
from .theory_handlers import *
from .other_handlers import *
from .echo_handlers import *
from .registration import *
